networks:
  dev:

services:
  ecommerce_api:
    depends_on:
      - "ecommerce_db"
      - "ecommerce_azurite"
      - "ecommerce_seq"
    container_name: ecommerce_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Host=ecommerce_db;User ID=postgres;Password=mysecretpassword;Server=ecommerce_db;Port=5432;Database=EcommerceDb
      - Serilog__WriteTo__1__Args__ServerUrl=http://ecommerce_seq:5341
      - BlobAzureStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ecommerce_azurite:10000/devstoreaccount1;QueueEndpoint=http://ecommerce_azurite:10001/devstoreaccount1;TableEndpoint=http://ecommerce_azurite:10002/devstoreaccount1;
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: ./Ecommerce/src/
      # dockerfile: ./src/Dockerfile
    # environment:
    #   - ConnectionStrings__Postgres=Host=localhost;User ID=postgres;Password=mysecretpassword;Server=ecommerce_db;Port=5432;Database=EcommerceDb
    networks:
      - dev
  ecommerce_db:
    image: postgres:latest
    container_name: ecommerce_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - "C:/Studia/Docker/EcommerceAPI/Postgres:/var/lib/postgresql/data"

  ecommerce_azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: ecommerce_azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - dev
    volumes:
      - "C:/Studia/Docker/EcommerceAPI/Azurite:/data"

  ecommerce_seq:
    image: datalust/seq:latest
    container_name: ecommerce_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8090:80"
    networks:
      - dev

  ecommerce_stripe:
    image: stripe/stripe-cli
    container_name: ecommerce_stripe
    command: listen --api-key sk_test_51PtprLCDEnJlTwZQPHr8DhSUaXhQCNlqHWaf5iJcOh3FCPOja6oU5S1l9uhPZkLEYkspelLMj5NFr9w5WFIBKPPT00eXRPMYwx --forward-to http://ecommerce_api:8080/api/webhooks/v1/carts-module/CheckoutCarts/checkout-session-completed
    networks:
      - dev
